/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 02 13:09:31 GMT 2024
 */

package examples;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import examples.ListComp02;
import examples.R;
import examples.S;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ListComp02_ESTest extends ListComp02_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ListComp02 listComp02_0 = new ListComp02();
      listComp02_0.clear();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ListComp02 listComp02_0 = new ListComp02();
      Integer integer0 = new Integer((-11));
      R r0 = new R(integer0, "");
      listComp02_0.insert_r(r0);
      S s0 = new S("", integer0);
      listComp02_0.insert_s(s0);
      Integer integer1 = listComp02_0.q();
      assertEquals(121, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ListComp02 listComp02_0 = new ListComp02();
      Integer integer0 = new Integer(0);
      S s0 = new S("", integer0);
      listComp02_0.insert_s(s0);
      listComp02_0.insert_r((R) null);
      // Undeclared exception!
      try { 
        listComp02_0.q();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("examples.ListComp02", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ArrayList<R> arrayList0 = new ArrayList<R>();
      ListComp02 listComp02_0 = new ListComp02(arrayList0, (ArrayList<S>) null);
      // Undeclared exception!
      try { 
        listComp02_0.insert_s((S) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("examples.ListComp02", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ListComp02 listComp02_0 = new ListComp02((ArrayList<R>) null, (ArrayList<S>) null);
      R r0 = new R((Integer) null, "@g6l''%#ISc`Wl<n");
      // Undeclared exception!
      try { 
        listComp02_0.insert_r(r0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("examples.ListComp02", e);
      }
  }
}
